// ============================================================
// «Вампиры: Маскарад» — готовые вампиры для быстрого старта.
// Листы собраны по правилам создания персонажа 5-й редакции:
// характеристики 4/3/2 по категориям, навыки по быстрому распределению,
// две клановые Дисциплины (2 и 1), стиль охоты с бонусными навыками,
// 7 пунктов фактов биографии, Человечность 7.
// ============================================================

import { VtmSheetData, VtmSkillState, VtmDisciplineState, VtmAdvantageEntry, SKILL_LIBRARY, DISCIPLINE_BY_ID, ADVANTAGE_BY_ID } from "./vtm-data";

export interface VtmTemplate {
  id: string;
  title: string;       // заголовок карточки выбора
  tagline: string;     // однострочная легенда
  portrait: string;    // путь к портрету из архива крови (public/vtm/portraits)
  sheet: {
    info: VtmSheetData["info"];
    attributes: VtmSheetData["attributes"];
    skills: { key: string; value: number; spec?: string }[];
    disciplines: { key: string; value: number; powers?: Record<number, string> }[];
    advantages: { id: string; rating: number; note?: string }[];
    gear: { haven: string; resources: string; items: { name: string; count: string; note?: string }[] };
    trackers: { humanity: number; hunger: number; xp: number };
  };
}

function skillName(key: string): string {
  return SKILL_LIBRARY.find((s) => s.id === key)?.name || key;
}

/** Собрать полный VtmSheetData из заготовки (серверная сборка — идемпотентно). */
export function buildTemplateSheet(templateId: string): VtmSheetData | null {
  const tpl = VTM_TEMPLATES.find((t) => t.id === templateId);
  if (!tpl) return null;
  const s = tpl.sheet;
  const skills: VtmSkillState[] = s.skills.map((sk) => ({
    key: sk.key,
    name: skillName(sk.key),
    value: sk.value,
    spec: sk.spec || "",
    xp: 0,
  }));
  const disciplines: VtmDisciplineState[] = s.disciplines.map((d) => ({
    key: d.key,
    name: DISCIPLINE_BY_ID.get(d.key)?.name || d.key,
    value: d.value,
    powers: d.powers ? { ...d.powers } : {},
    xp: 0,
  }));
  const advantages: VtmAdvantageEntry[] = s.advantages.map((a, i) => ({
    id: `tpl-${a.id}-${i}`,
    name: ADVANTAGE_BY_ID.get(a.id)?.name || a.id,
    kind: ADVANTAGE_BY_ID.get(a.id)?.kind || "background",
    rating: a.rating,
    note: a.note || "",
  }));
  return {
    info: { ...s.info, portrait: tpl.portrait, portraitThumb: tpl.portrait },
    attributes: { ...s.attributes },
    skills,
    disciplines,
    advantages,
    loresheets: [],
    diablerie: { count: 0, notes: "" },
    advV2: true,
    gear: {
      haven: s.gear.haven,
      resources: s.gear.resources,
      items: s.gear.items.map((it, i) => ({ id: `tpl-item-${i}`, name: it.name, count: it.count, note: it.note || "" })),
    },
    notes: { draft: "", entries: [] },
    trackers: {
      humanity: s.trackers.humanity,
      stains: 0,
      hunger: s.trackers.hunger,
      healthSup: 0,
      healthAgg: 0,
      wpSup: 0,
      wpAgg: 0,
      xp: s.trackers.xp,
      xpSpent: 0,
      huntCount: 0,
      lastHunt: "",
    },
    rollLog: [],
    xpLog: [],
    resonance: { kind: "", intensity: 0 },
    // Новые механики (V5 Companion / Gehenna War / In Memoriam)
    bonds: [],
    coterie: { name: "", type: "", tieKind: "", tieNote: "", clanMerit: "", members: [] },
    boons: [],
    convictions: [],
    torpor: { inTorpor: false, since: "", humanity: s.trackers.humanity, note: "" },
    conditions: [],
  };
}

export const VTM_TEMPLATES: VtmTemplate[] = [
  {
    id: "brujah-rebel",
    title: "Анарх-бунтарь",
    tagline: "Кулак фрифольда: бьёт первым, извиняется никогда",
    portrait: "/vtm/portraits/brujah-anarch.jpg",
    sheet: {
      info: {
        name: "Аякс Каменный",
        concept: "Бывший боксёр-подпольщик, ныне ударный кулак анархов",
        chronicle: "",
        sire: "Роза Гварда, пропала после рейда Камарильи",
occupation: "боксёр подпольных боёв, ныне ударный кулак фрифольда",
        generation: 12,
        sect: "anarch",
        clan: "brujah",
        predator: "raider",
        ambition: "Свергнуть Принца и переустроить город по-своему",
        desire: "Проверить, кто из «друзей» продал Рову Камарилье",
        principle1: "Никогда не бью того, кто не может ответить",
        principle2: "Всегда доканчиваю драку",
        principle3: "Никогда не предаю своих",
        anchor1: "Сестра Лера, студентка, не знает, чем я стал",
        anchor2: "Старый тренер Яша, держит зал на окраине",
        anchor3: "Бар «Ринг», где котерия собирается по ночам",
        description: "Двухметровый верзила со сломанным носом и шрамом через бровь. Костяшки вечной красные. Двигается спокойно, как перед первым раундом.",
        history: "Аякс боксировал за деньги подземных боёв, пока его не заметила Роза — бруха с репутацией грозы Элизиума. Становление прошло в подвале зала: он умер в пятницу, а в субботу уже побил своего первого сира-обидчика. Теперь его имя — аргумент фрифольда в переговорах с Камарильей.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 4, dex: 3, sta: 3, cha: 2, man: 2, com: 2, int: 2, wit: 3, res: 1 },
      skills: [
        { key: "brawl", value: 4, spec: "уличный бой" },
        { key: "melee", value: 2, spec: "подручное железо" },
        { key: "intimidation", value: 3, spec: "молчаливый взгляд" },
        { key: "athletics", value: 2, spec: "рывок" },
        { key: "firearms", value: 1 },
        { key: "streetwise", value: 2, spec: "бои без правил" },
        { key: "awareness", value: 2, spec: "засады" },
        { key: "drive", value: 1 },
        { key: "stealth", value: 1 },
        { key: "persuasion", value: 1 },
        { key: "survival", value: 1 },
      ],
      disciplines: [
        { key: "potence", value: 2, powers: { 1: "Смертоносность", 2: "Сокрушение" } },
        { key: "celerity", value: 1, powers: { 1: "Быстрая реакция" } },
        { key: "presence", value: 1, powers: { 1: "Угроза" } },
      ],
      advantages: [
        { id: "allies", rating: 2, note: "Зал Яши: полдюжины крепких парней" },
        { id: "contacts", rating: 2, note: "Букмекер Сеня знает, где чьи деньги" },
        { id: "status", rating: 2, note: "Признанный боец фрифольда" },
        { id: "repulsive", rating: 1 },
      ],
      gear: {
        haven: "Подвал боксового зала Яши: стиральная машина, стопка матрасов, засовы",
        resources: "Сбережения боёв, немного налички от котерии",
        items: [
          { name: "Бинт и аптечка", count: "1" },
          { name: "Бита из дуба", count: "1", note: "Подарок Яши на Становление" },
          { name: "Телефон в пакете", count: "1" },
          { name: "Бутылка бетона… то есть цемента", count: "1" },
        ],
      },
      trackers: { humanity: 6, hunger: 2, xp: 0 },
    },
  },
  {
    id: "ventru-executive",
    title: "Корпоративный хищник",
    tagline: "Днём — совет директоров, ночью — совет клана",
    portrait: "/vtm/portraits/ventrue-corporate.jpg",
    sheet: {
      info: {
        name: "Виктория Крейн",
        concept: "Инвестиционный директор с вечным пропуском в ночную смену",
        chronicle: "",
        sire: "Огастес Прайд, старейшина, трижды в неделю на связи",
occupation: "инвестиционный директор, правая рука клана в финансах",
        generation: 11,
        sect: "camarilla",
        clan: "ventru",
        predator: "gentleman",
        ambition: "Войти в совет Первых городов и переписать устав наследства Прайда",
        desire: "Дожать слияние, не оставив следов для аудита",
        principle1: "Никогда не подписываю то, что не смогу отнять",
        principle2: "Всегда плачу долг — кровью или деньгами",
        principle3: "Никогда не пью из одного сосуда дважды без уз",
        anchor1: "Ассистентка Мила: считает, что шеф просто «ночная работа»",
        anchor2: "Бывший муж Дэвид, подписал бумаги о молчании",
        anchor3: "Сад на крыше офиса — единственное место, где она думает",
        description: "Идеальный деловой костюм, ни одной морщины. Взгляд, который первым делом ищет в человеке слабость активов. Кофе в руке — чёрный, остывший, для вида.",
        history: "Виктория закрывала заводы, пока не открыла, что сама становится активом. Огастес купил её компанию, её долги и её жизнь одним ужином. Теперь она управляет капиталами клана и знает, что «пенсия» вентру называется торпором.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 1, dex: 2, sta: 2, cha: 3, man: 3, com: 4, int: 3, wit: 2, res: 2 },
      skills: [
        { key: "finance", value: 4, spec: "слияния и поглощения" },
        { key: "persuasion", value: 3, spec: "переговоры" },
        { key: "politics", value: 3, spec: "Камарилья" },
        { key: "etiquette", value: 2, spec: "Элизиум" },
        { key: "subterfuge", value: 2, spec: "легенды" },
        { key: "leadership", value: 2 },
        { key: "insight", value: 2, spec: "ложь" },
        { key: "academics", value: 1 },
        { key: "awareness", value: 1 },
        { key: "firearms", value: 1 },
        { key: "technology", value: 1 },
        { key: "drive", value: 1 },
      ],
      disciplines: [
        { key: "dominate", value: 2, powers: { 1: "Провал в памяти", 2: "Внушение" } },
        { key: "presence", value: 1, powers: { 1: "Благоговение" } },
        { key: "fortitude", value: 1, powers: { 1: "Сила жизни" } },
      ],
      advantages: [
        { id: "resources", rating: 3, note: "Семейный фонд Крейн, запасной счёт" },
        { id: "influence", rating: 2, note: "Налоговая и один замминиста" },
        { id: "mask", rating: 2, note: "«Вера Крейн», второе гражданство" },
      ],
      gear: {
        haven: "Пентхаус с тонированными витринами и склепом в паркинге",
        resources: "Дивиденды, серые схемы, карточка «на мелочи» в 40 тысяч",
        items: [
          { name: "Платиновая карта", count: "1" },
          { name: "Телефон с двумя симками", count: "1", note: "Одна для смертных, вторая для котерии" },
          { name: "Ручка, подписывающая сама", count: "1", note: "Сувенир от сира" },
          { name: "Список должников", count: "1" },
        ],
      },
      trackers: { humanity: 6, hunger: 1, xp: 0 },
    },
  },
  {
    id: "toreador-artist",
    title: "Вечная художница",
    tagline: "Пишет ночь так, что она отвечает взаимностью",
    portrait: "/vtm/portraits/toreador-artist.jpg",
    sheet: {
      info: {
        name: "Изольда Марр",
        concept: "Галерист, чьи вернисажи начинаются после заката",
        chronicle: "",
        sire: "Селестин, куратор из Лиона, писал её портрет 40 лет",
occupation: "галеристка и художница, законодатель вкуса Элизиума",
        generation: 12,
        sect: "camarilla",
        clan: "toreador",
        predator: "siren",
        ambition: "Собрать коллекцию, которую увидит наступающая Геенна",
        desire: "Добыть для выставки «утраченный» холст из частного склепа",
        principle1: "Никогда не порчу искусство — ничьё",
        principle2: "Всегда заплачу художнику, даже посмертно",
        principle3: "Никогда не хвалю лестью",
        anchor1: "Молодой живописец Ким, её «протеже» и сосуд",
        anchor2: "Сестра в другом городе — пишет ей письма, не отправляя",
        anchor3: "Галерея «Полночь» — стены помнят каждую её ночь",
        description: "Чёрное платье с красным шлейфом-мазком. Движется, как экспозиция: медленно и нарочно. Улыбка — та, что делает цену картины вдвое выше.",
        history: "Изольда умерла в 1924-м с верёвкой на шее и недописанным портретом. Селестин поднял её из петли и научил видеть красоту в том, что вяло умирает. С тех пор её галерея меняет город — а город платит кровью.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 1, dex: 2, sta: 2, cha: 4, man: 3, com: 3, int: 3, wit: 2, res: 2 },
      skills: [
        { key: "craft", value: 4, spec: "живопись" },
        { key: "performance", value: 2, spec: "вернисажи" },
        { key: "persuasion", value: 3, spec: "цена красоты" },
        { key: "subterfuge", value: 2, spec: "соблазнение" },
        { key: "etiquette", value: 3, spec: "Элизиум" },
        { key: "academics", value: 2, spec: "история искусств" },
        { key: "insight", value: 2, spec: "эмоции" },
        { key: "awareness", value: 2, spec: "детали" },
        { key: "finance", value: 1 },
        { key: "stealth", value: 1 },
        { key: "melee", value: 1 },
        { key: "occult", value: 1 },
      ],
      disciplines: [
        { key: "auspex", value: 2, powers: { 1: "Обострение чувств", 2: "Предвестие" } },
        { key: "celerity", value: 1, powers: { 1: "Кошачья грация" } },
        { key: "presence", value: 1, powers: { 1: "Незабываемый поцелуй" } },
      ],
      advantages: [
        { id: "resources", rating: 2, note: "Галерея, запас краски и денег" },
        { id: "fame", rating: 2, note: "«Та самая Марр» в светской хронике" },
        { id: "herd", rating: 2, note: "Молодые художники, желающие «натуру»" },
        { id: "beauty", rating: 1 },
      ],
      gear: {
        haven: "Квартира над галереей: спальня без окон, стена с портретом сира",
        resources: "Продажи галереи, трастовый фонд 1924 года",
        items: [
          { name: "Набор кистей и красок", count: "1", note: "Свинцовые белила сира" },
          { name: "Пригласительные на вернисаж", count: "6" },
          { name: "Дневник с зарисовками города", count: "1" },
          { name: "Антикварное зеркало", count: "1", note: "Не отражает. Она всё равно смотрится." },
        ],
      },
      trackers: { humanity: 7, hunger: 1, xp: 0 },
    },
  },
  {
    id: "malkavian-oracle",
    title: "Уличный пророк",
    tagline: "Сеть Малкава шепчет ему чужие сны нараспев",
    portrait: "/vtm/portraits/malkavian-prophet.jpg",
    sheet: {
      info: {
        name: "Тихон",
        concept: "Бывший дежурный по станции метро, теперь слушает город",
        chronicle: "",
        sire: "«Женщина в жёлтом», появляется раз в год, платит за кофе",
occupation: "бывший дежурный метро, ныне слушатель города",
        generation: 13,
        sect: "camarilla",
        clan: "malkavian",
        predator: "morpheus",
        ambition: "Услышать голос города целиком и понять, что он предвещает",
        desire: "Найти пропавшую пассажирку с жетоном 1978 года",
        principle1: "Никогда не вру тому, кто спит",
        principle2: "Всегда докладываю Сети о глазах инквизиции",
        principle3: "Никогда не поднимаюсь на эскалаторе против хода",
        anchor1: "Диспетчер Галя, смена «спать нельзя — слушай»",
        anchor2: "Кот Метро, чёрный, появляется перед бедой",
        anchor3: "Платформа «Конечная», где линия заканчивается и начинается",
        description: "Форменная куртка с чужим именем на бейджике. Глаза следят за тем, чего нет. Говорит вполголоса, будто боится перебить город.",
        history: "Тихон умер на смене: столкновение, темнота, голос в тоннеле. Женщина в жёлтом нашла его раньше медиков. Теперь он слышит станции как орган, а Сеть Малкава держит его за руку на каждой ветке.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 1, dex: 2, sta: 2, cha: 2, man: 2, com: 3, int: 4, wit: 3, res: 3 },
      skills: [
        { key: "awareness", value: 4, spec: "голоса города" },
        { key: "occult", value: 2, spec: "приметы" },
        { key: "insight", value: 3, spec: "страх" },
        { key: "investigation", value: 2, spec: "улики" },
        { key: "stealth", value: 2, spec: "тени города" },
        { key: "larceny", value: 2, spec: "обход сигнализации" },
        { key: "academics", value: 1 },
        { key: "technology", value: 2, spec: "камеры" },
        { key: "streetwise", value: 2, spec: "сарафанное радио" },
        { key: "subterfuge", value: 1 },
        { key: "survival", value: 1 },
        { key: "medicine", value: 1 },
      ],
      disciplines: [
        { key: "auspex", value: 2, powers: { 1: "Потустороннее зрение" } },
        { key: "dominate", value: 1, powers: { 1: "Провал в памяти" } },
        { key: "obfuscate", value: 1, powers: { 1: "Плащ теней" } },
      ],
      advantages: [
        { id: "contacts", rating: 3, note: "Службы метро, ночь охраны, блогеры-сталкеры" },
        { id: "allies", rating: 2, note: "Собрат по Сети — голос на проводе" },
        { id: "haven", rating: 2, note: "Камера-кладовая под платформой" },
      ],
      gear: {
        haven: "Техническая камера под конечной: рельса как кровать, жетоны как наличные",
        resources: "Найденные кошельки, копилки жетонов",
        items: [
          { name: "Фонарь с красным светофильтром", count: "1" },
          { name: "Стопка старых жетонов", count: "1978 шт.", note: "Один из них — её" },
          { name: "Рация «Гранит»", count: "1", note: "Ловит чужие частоты" },
          { name: "Блокнот предсказаний", count: "1" },
        ],
      },
      trackers: { humanity: 7, hunger: 2, xp: 0 },
    },
  },
  {
    id: "nosferatu-broker",
    title: "Торговец тайнами",
    tagline: "Продаст любого — и купит всех",
    portrait: "/vtm/portraits/nosferatu-broker.jpg",
    sheet: {
      info: {
        name: "Крот",
        concept: "Легенда городских подземелий, инфоброкер без лица",
        chronicle: "",
        sire: "Неизвестен: проснулся уже под землёй, сир оставил только письмо",
occupation: "инфоброкер городских подземелий, «сантехник ЖЭКа»",
        generation: 12,
        sect: "camarilla",
        clan: "nosferatu",
        predator: "graverobber",
        ambition: "Собрать архив тайн, который сделает его неприкасаемым",
        desire: "Узнать, кто его сир — и зачем тот всё ещё пишет",
        principle1: "Никогда не отдаю источник",
        principle2: "Всегда беру оплату вперёд",
        principle3: "Никогда не выхожу на поверхность до полуночи",
        anchor1: "Слепая продавщица цветов Зина, единственная, кто жмёт руку",
        anchor2: "Ученик Питон, роет новые тоннели",
        anchor3: "Старое бомбоубежище — стены помнят ещё его первые ночи",
        description: "Не виден под плащом: серая кожа, впалые щёки, зубы в два ряда. Пахнет землёй и старой водой. Говорит ласково — это пугает сильнее уродства.",
        history: "Крот не помнит своего смертного имени. Он проснулся в бетонной норе с письмом: «Твоё имя теперь — то, что я сказал бы тебе, если бы захотел». С тех пор он собирает чужие имена и продаёт их дороже золота.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 2, dex: 2, sta: 2, cha: 1, man: 3, com: 3, int: 4, wit: 3, res: 2 },
      skills: [
        { key: "stealth", value: 3, spec: "тени города" },
        { key: "larceny", value: 3, spec: "вскрытие замков" },
        { key: "investigation", value: 4, spec: "архивы" },
        { key: "technology", value: 3, spec: "цифровая слежка" },
        { key: "streetwise", value: 3, spec: "сарафанное радио" },
        { key: "occult", value: 2, spec: "ритуалы" },
        { key: "awareness", value: 2, spec: "охотников" },
        { key: "insight", value: 2, spec: "зависимости" },
        { key: "politics", value: 2, spec: "интриги Элизиума" },
        { key: "animal_ken", value: 1 },
        { key: "melee", value: 1 },
        { key: "finance", value: 1 },
      ],
      disciplines: [
        { key: "obfuscate", value: 2, powers: { 1: "Безмолвие смерти" } },
        { key: "animalism", value: 1, powers: { 1: "Фамулус" } },
      ],
      advantages: [
        { id: "contacts", rating: 4, note: "От дворников до архивисток" },
        { id: "mask", rating: 2, note: "«Дядя Коля», сантехник ЖЭКа" },
        { id: "herd", rating: 1, note: "Патологоанатом с «излишками»" },
      ],
      gear: {
        haven: "Бомбоубежище под теплотрассой: серверы, картотеки, запас воды",
        resources: "Крипта, наличка в тубусах, долги с процентами",
        items: [
          { name: "Ноутбук в чехле от воды", count: "1" },
          { name: "Картотека источников", count: "1", note: "Бумажная — computers сгорают, бумага нет" },
          { name: "Пакет донорской крови", count: "3" },
          { name: "Письмо сира", count: "1", note: "Читал 400 раз" },
        ],
      },
      trackers: { humanity: 6, hunger: 1, xp: 0 },
    },
  },
  {
    id: "gangrel-pathfinder",
    title: "Следопыт окраин",
    tagline: "Зверь идёт рядом — и молчит из уважения",
    portrait: "/vtm/portraits/gangrel-tracker.jpg",
    sheet: {
      info: {
        name: "Рада Волкова",
        concept: "Егерь заповедника, которая видела слишком много ночью",
        chronicle: "",
        sire: "Старый Гонец, пришёл с востока и ушёл дальше на восток",
occupation: "егерь заповедника, следопыт окраин",
        generation: 12,
        sect: "autarkis",
        clan: "gangrel",
        predator: "farmer",
        ambition: "Найти место, где Зверь и она уравняются",
        desire: "Выследить тварь, что режет скот по всей области",
        principle1: "Никогда не убиваю то, что могу переждать",
        principle2: "Всегда кормлю тех, кто кормит меня",
        principle3: "Никогда не сплю в одном логове дважды",
        anchor1: "Лошадь Бура, единственная, кто помнит её тепло",
        anchor2: "Лесник Дёмин, оставляет в сторожке спички",
        anchor3: "Сторожка у болота — метки на двери ведут счёт ночам",
        description: "Обветренное лицо, глаза жёлтые в темноте. Одежда — слоями, по погоде и без. Кожаные перчатки скрывают когти, но не всегда.",
        history: "Рада выслеживала браконьеров, пока однажды не выследила того, кто не был человеком. Гонец неделю учил её молчать с Зверем — и ушёл на рассвете. Теперь она ходит по окраинам города, где асфальт кончается и начинается правда.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 2, dex: 4, sta: 3, cha: 2, man: 1, com: 2, int: 2, wit: 3, res: 3 },
      skills: [
        { key: "survival", value: 4, spec: "лес" },
        { key: "athletics", value: 3, spec: "скалолазание" },
        { key: "animal_ken", value: 3, spec: "хищники" },
        { key: "stealth", value: 3, spec: "засады" },
        { key: "brawl", value: 2, spec: "борьба" },
        { key: "melee", value: 2, spec: "ножи" },
        { key: "firearms", value: 2, spec: "винтовки" },
        { key: "awareness", value: 3, spec: "засады" },
        { key: "drive", value: 1 },
        { key: "medicine", value: 1 },
        { key: "occult", value: 1 },
        { key: "intimidation", value: 1 },
      ],
      disciplines: [
        { key: "protean", value: 2, powers: { 1: "Глаза зверя", 2: "Оружие зверя" } },
        { key: "animalism", value: 1, powers: { 1: "Чутьё на Зверя" } },
        { key: "fortitude", value: 1, powers: { 1: "Сила жизни" } },
      ],
      advantages: [
        { id: "allies", rating: 2, note: "Дёмин и его рейдовые" },
        { id: "haven", rating: 3, note: "Сеть сторожек от болота до карьеры" },
        { id: "contacts", rating: 2, note: "Ветеринары, егеря, дальнобойщики" },
      ],
      gear: {
        haven: "Сторожка у болота: печь, солома, колыбель из земли в сарае",
        resources: "Сдача шкур, немного денег от Дёмина",
        items: [
          { name: "Нож с костяной рукоятью", count: "1", note: "Клинок Гонца" },
          { name: "Винтовка «Тигр»", count: "1" },
          { name: "Фляга из желудя", count: "1" },
          { name: "Мешок родной земли", count: "1", note: "Из-под старой сосны" },
        ],
      },
      trackers: { humanity: 7, hunger: 1, xp: 0 },
    },
  },
  {
    id: "tremere-sorcerer",
    title: "Чародей крови",
    tagline: "Пирамида пала — формулы остались",
    portrait: "/vtm/portraits/tremere-sorcerer.jpg",
    sheet: {
      info: {
        name: "Альба Грант",
        concept: "Научный сотрудник закрытой кафедры, варит витэ по методичкам",
        chronicle: "",
        sire: "Регент Аврелий, требует отчёты каждую новолуние",
occupation: "научный сотрудник кафедры, чародейка Крови",
        generation: 11,
        sect: "camarilla",
        clan: "tremere",
        predator: "clansman",
        ambition: "Восстановить лабораторию Пирамиды и найти предателя Вены",
        desire: "Записать ритуал, который не сгорел в архивном пожаре",
        principle1: "Никогда не повторяю эксперимент вслепую",
        principle2: "Всегда плачу за кровь — ровно и честно",
        principle3: "Никогда не заговариваю о Пирамиде с чужаками",
        anchor1: "Лаборантка Женя: верит, что шеф «работает с донорами»",
        anchor2: "Брат Эндрю, хранит её смертные вещи",
        anchor3: "Лаборатория в подвале кафедры — реактивы пахнут как дом",
        description: "Белый халат поверх чёрного костюма. Пальцы в старых ожогах от щёлочи и огня ритуалов. Очки — без диоптрий, чтобы прятать взгляд.",
        history: "Альба защитила диссертацию по гемохимии в неделю до того, как Аврелий предложил ей «долгосрочный грант». Кровь оказалась сложнее гель-хроматографии. Теперь её отчёты ждут в Вене — и кто-то в Пирамиде уже выделил её имя красным.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 1, dex: 2, sta: 2, cha: 2, man: 2, com: 3, int: 4, wit: 3, res: 3 },
      skills: [
        { key: "occult", value: 4, spec: "ритуалы" },
        { key: "science", value: 3, spec: "химия" },
        { key: "medicine", value: 2, spec: "токсикология" },
        { key: "academics", value: 3, spec: "история" },
        { key: "investigation", value: 2, spec: "улики" },
        { key: "politics", value: 2, spec: "Камарилья" },
        { key: "technology", value: 1 },
        { key: "insight", value: 2, spec: "эмоции" },
        { key: "persuasion", value: 1 },
        { key: "firearms", value: 1 },
        { key: "larceny", value: 1 },
        { key: "awareness", value: 1 },
      ],
      disciplines: [
        { key: "blood_sorcery", value: 2, powers: { 1: "Вкус крови", 2: "Истончение витэ" } },
        { key: "auspex", value: 1, powers: { 1: "Обострение чувств" } },
        { key: "dominate", value: 2, powers: { 1: "Принуждение" } },
      ],
      advantages: [
        { id: "resources", rating: 2, note: "Грант кафедры, «спонсорские» от клана" },
        { id: "herd", rating: 2, note: "Доноры-добровольцы кафедры" },
        { id: "mawla", rating: 3, note: "Регент Аврелий — наставник и надзиратель" },
      ],
      gear: {
        haven: "Лаборатория-склеп под кафедрой: рефрижератор, алтарь-вытяжка",
        resources: "Бюджет проекта «Биохимия сна», наличка от ритуалов",
        items: [
          { name: "Аптечка для забора крови", count: "1" },
          { name: "Термостат с пробирками", count: "1", note: "Метки дат — по ночам полнолуния" },
          { name: "Гримуар в переплёте из ксерокса", count: "1", note: "Оригинал сгорел с архивом" },
          { name: "Пропуск в морг", count: "1" },
        ],
      },
      trackers: { humanity: 7, hunger: 1, xp: 0 },
    },
  },
  {
    id: "banu-haqim-judge",
    title: "Судья ночи",
    tagline: "Бану Хаким: клинок правосудия в тени закона",
    portrait: "/vtm/portraits/banu-haqim-assassin.jpg",
    sheet: {
      info: {
        name: "Тарик аль-Хашим",
        concept: "Наследник древнего рода ассасинов, судья в современном городе",
        chronicle: "",
        sire: "Шейх Ибрагим, председатель суда старейшин Бану Хаким",
        occupation: "юридический консультант при дворе Принца",
        generation: 11,
        sect: "camarilla",
        clan: "banu_haqim",
        predator: "blood_leech",
        ambition: "Восстановить справедливость над теми, кто избежал суда смертных",
        desire: "Найти Сородича, что убил его смертного брата двадцать лет назад",
        principle1: "Правосудие превыше крови",
        principle2: "Никогда не убивай без приговора",
        principle3: "Слово данное — вечное",
        anchor1: "Дочь Лейла, прокурор, не знает о его природе",
        anchor2: "Старый судья Омар, наставник в праве",
        anchor3: "Мечеть на окраине, где он молится (или притворяется)",
        description: "Стройный мужчина с острыми чертами лица, короткой бородой и тёмными глазами. Движется бесшумно, как кошка. На мизинце — перстень с печатью Хашим.",
        history: "Тарик родился в семье потомственных ассасинов Бану Хаким. Становление принял в 25 лет, после того как шейх Ибрагим признал в нём кровь Хашима. Изучал право в Каире и Стамбуле, теперь служит «юридическим советником» при дворе Принца — но его настоящий долг — суд над теми, кого не достало земное правосудие.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 3, dex: 4, sta: 3, cha: 2, man: 3, com: 3, int: 3, wit: 3, res: 2 },
      skills: [
        { key: "melee", value: 3, spec: "клинок ассасина" },
        { key: "stealth", value: 3, spec: "ночная слежка" },
        { key: "investigation", value: 2, spec: "улики" },
        { key: "subterfuge", value: 2, spec: "двойная игра" },
        { key: "intimidation", value: 2, spec: "холодный взгляд" },
        { key: "academics", value: 2, spec: "исламское право" },
        { key: "streetwise", value: 2, spec: "тени города" },
        { key: "athletics", value: 2, spec: "бег по крышам" },
        { key: "awareness", value: 2, spec: "засады" },
        { key: "insight", value: 1 },
      ],
      disciplines: [
        { key: "celerity", value: 2, powers: { 1: "Быстрая реакция", 2: "Проворство" } },
        { key: "blood_sorcery", value: 1, powers: { 1: "Кровавый знак" } },
        { key: "auspex", value: 1, powers: { 1: "Обострение чувств" } },
      ],
      advantages: [
        { id: "status", rating: 2, note: "Архонт Бану Хаким при дворе Принца" },
        { id: "contacts", rating: 3, note: "Сеть информаторов в диаспоре" },
        { id: "allies", rating: 2, note: "Двое братьев по крови" },
        { id: "haven", rating: 2, note: "Квартира над юридической конторой" },
        { id: "cc_banu_haqim", rating: 1 },
      ],
      gear: {
        haven: "Юридическая контора «аль-Хашим и партнёры» — прикрытие и убежище",
        resources: "Счета семьи в трёх банках",
        items: [
          { name: "Клинок ассасина", count: "1", note: "Ритуальный ятаган, благословлённый кровью сира" },
          { name: "Перстень-печать", count: "1", note: "Печать Хашим, знак верности клану" },
          { name: "Чётки", count: "1", note: "Бывают полезны для молитвы... или для счета жертв" },
        ],
      },
      trackers: { humanity: 6, hunger: 1, xp: 0 },
    },
  },
  {
    id: "lasombra-shadow",
    title: "Тень престола",
    tagline: "Ласомбра: тот, кто правит из-за трона",
    portrait: "/vtm/portraits/lasombra-noble.jpg",
    sheet: {
      info: {
        name: "Дон Алессандро де ла Крус",
        concept: "Испанский аристократ, перешедший из Саббата в Камарилью",
        chronicle: "",
        sire: "Донна Изабелла, пала в огне Инквизиции 1923",
        occupation: "финансовый советник при дворе Принца",
        generation: 10,
        sect: "camarilla",
        clan: "lasombra",
        predator: "gentleman",
        ambition: "Сделать Камарилью своей марионеткой, как прежде Саббат",
        desire: "Уничтожить последнего арпая, что помнит его по Саббату",
        principle1: "Власть — единственная добродетель",
        principle2: "Тень шагает первой",
        principle3: "Никогда не доверяй свету",
        anchor1: "Вдова Кармен, бывшая любовница, не знает, что он жив",
        anchor2: "Церковь Святого Иакова, где он когда-то молился",
        anchor3: "Семейный склеп де ла Крус в Севилье",
        description: "Высокий испанец с аристократическими чертами, седеющими висками и холодными серыми глазами. Чёрный бархатный сюртук. Тени вокруг него всегда гуще, чем должны быть.",
        history: "Дон Алессандро родился в 1860 в аристократической семье Севильи. Становление принял от Донны Изабеллы в 1898, вступил в Саббат. После падения Мадридского епископа в 2008 перешёл в Камарилью — «для выгоды», как он говорит. Его тени давно научились шептать ему секреты врагов.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 2, dex: 3, sta: 2, cha: 3, man: 4, com: 4, int: 3, wit: 3, res: 3 },
      skills: [
        { key: "subterfuge", value: 4, spec: "двойная игра" },
        { key: "etiquette", value: 3, spec: "двор Принца" },
        { key: "persuasion", value: 3, spec: "тонкий намёк" },
        { key: "intimidation", value: 2, spec: "холодное молчание" },
        { key: "finance", value: 3, spec: "старые деньги" },
        { key: "politics", value: 3, spec: "интриги Камарильи" },
        { key: "insight", value: 2, spec: "ложь" },
        { key: "leadership", value: 2, spec: "шёпот из тени" },
        { key: "melee", value: 1, spec: "рапира" },
      ],
      disciplines: [
        { key: "oblivion", value: 2, powers: { 1: "Шёпот Бездны", 2: "Покров тьмы" } },
        { key: "dominate", value: 2, powers: { 1: "Команда", 2: "Мозоль памяти" } },
        { key: "presence", value: 1, powers: { 1: "Угроза" } },
      ],
      advantages: [
        { id: "status", rating: 3, note: "Бывший архиепископ Саббата, ныне советник Принца" },
        { id: "resources", rating: 4, note: "Семейные поместья в Испании и Италии" },
        { id: "contacts", rating: 3, note: "Банкиры, дипломаты, старая аристократия" },
        { id: "haven", rating: 3, note: "Пентхаус в историческом центре, окна на север" },
        { id: "cc_lasombra", rating: 1 },
        { id: "other_dark_secret", rating: 1, note: "Знает, кто подложил бомбу в Мадрид в 2008" },
      ],
      gear: {
        haven: "Пентхаус в историческом здании, окна всегда закрыты шторами",
        resources: "Семейный траст в Цюрихе, поместья в Европе",
        items: [
          { name: "Перстень с печаткой", count: "1", note: "Герб де ла Крус, иногда — фокус для Забвения" },
          { name: "Чёрный бархатный сюртук", count: "1", note: "Сшит в 1920, всё ещё как новый" },
          { name: "Старый дневник", count: "1", note: "Имена всех, кого он предал — и кто предал его" },
        ],
      },
      trackers: { humanity: 5, hunger: 1, xp: 0 },
    },
  },
  {
    id: "hecata-mourner",
    title: "Плакальщица",
    tagline: "Геката: хранительница последнего перехода",
    portrait: "/vtm/portraits/hecata-necromancer.jpg",
    sheet: {
      info: {
        name: "Маргерита Джованни",
        concept: "Некромантка семьи смерти, хранительница последнего пути",
        chronicle: "",
        sire: "Дон Витторио, прадед, ушёл в торпор в 1998",
        occupation: "распорядитель похоронного бюро «Джованни и сыновья»",
        generation: 12,
        sect: "camarilla",
        clan: "hecata",
        predator: "graverobber",
        ambition: "Собрать все души семьи, что блуждают в Бездне",
        desire: "Найти способ поговорить с прадедом в торпоре",
        principle1: "Мёртвые заслуживают уважения",
        principle2: "Никогда не лги мертвецу",
        principle3: "Семья — выше всего, даже после смерти",
        anchor1: "Племянница Беа, студентка-медик, не знает о семье",
        anchor2: "Старое кладбище Сан-Микеле, где она гуляет с детства",
        anchor3: "Кот Чезаре, чёрный, видит духов",
        description: "Худая бледная женщина в чёрном трауре, с тёмными кругами под глазами. Чёрное кружево закрывает пол-лица. Костяные чётки на запястье. Пахнет лилиями и холодной землёй.",
        history: "Маргерита родилась в 1975 в венецианской ветви Джованни. Становление приняла в 25, после того как прадед Дон Витторио увидел в ней «дар слышать мёртвых». После Объединения Семьи (Family Reunion) 2018 осталась верна Гекате. Ведёт похоронное бюро — легальный источник тел для ритуалов.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 1, dex: 2, sta: 2, cha: 2, man: 3, com: 3, int: 4, wit: 3, res: 3 },
      skills: [
        { key: "occult", value: 4, spec: "некромантия Джованни" },
        { key: "medicine", value: 3, spec: "вскрытие и бальзамирование" },
        { key: "academics", value: 2, spec: "история семьи" },
        { key: "insight", value: 2, spec: "читать скорбь" },
        { key: "etiquette", value: 2, spec: "траурный протокол" },
        { key: "subterfuge", value: 2, spec: "вежливая ложь" },
        { key: "craft", value: 1, spec: "гробы" },
        { key: "awareness", value: 2, spec: "присутствие духов" },
      ],
      disciplines: [
        { key: "oblivion", value: 3, powers: { 1: "Шёпот Бездны", 2: "Покров тьмы", 3: "Зов духа" } },
        { key: "auspex", value: 2, powers: { 1: "Обострение чувств", 2: "Предвестие" } },
        { key: "fortitude", value: 1, powers: { 1: "Устойчивость" } },
      ],
      advantages: [
        { id: "status", rating: 2, note: "Капо семьи Геката в городе" },
        { id: "herd", rating: 3, note: "Покойники похоронного бюро — кровь ещё тёплая" },
        { id: "haven", rating: 3, note: "Похоронное бюро с моргом и крематорием" },
        { id: "retainers", rating: 2, note: "Два гуля-могильщика" },
        { id: "cc_hecata", rating: 1 },
      ],
      gear: {
        haven: "Похоронное бюро «Джованни и сыновья» — морг, крематорий, подземный зал ритуалов",
        resources: "Семейный траст + доходы похоронного бюро",
        items: [
          { name: "Костяные чётки", count: "1", note: "Из костей прадеда, фокус для Забвения" },
          { name: "Серебряный кубок", count: "1", note: "Для ритуалов разговоров с мёртвыми" },
          { name: "Книга мёртвых", count: "1", note: "Семейный кодекс некромантии, в кожаном переплёте" },
          { name: "Чёрное креповое платье", count: "1", note: "Траурный наряд, носит всегда" },
        ],
      },
      trackers: { humanity: 6, hunger: 2, xp: 0 },
    },
  },
  {
    id: "ministry-tempter",
    title: "Искуситель",
    tagline: "Министерство Сета: шёпот, что будит древнее",
    portrait: "/vtm/portraits/ministry-priest.jpg",
    sheet: {
      info: {
        name: "Нефтис Сета",
        concept: "Жрица культа Сета, что соблазняет города грехом",
        chronicle: "",
        sire: "Анубис, верховный жрец храма Сета в Каире",
        occupation: "владелица эзотерического бутика и салона «Лотос»",
        generation: 11,
        sect: "anarch",
        clan: "ministry",
        predator: "siren",
        ambition: "Разбудить Сета в каждом городе через ритуалы искушения",
        desire: "Найти «Книгу Венерирующего Змея», украденную Инквизицией",
        principle1: "Искушение — путь к свободе",
        principle2: "Никогда не отказывай в удовольствии",
        principle3: "Сет освободит верных",
        anchor1: "Младший брат Амон, музыкант, не знает о её природе",
        anchor2: "Храм Сета в Каире, место паломничества",
        anchor3: "Салон «Лотос», где она собирает поклонников",
        description: "Стройная женщина с бронзовой кожей и раскосыми глазами, подведёнными сурьмой. Чёрные волосы заплетены в сложную косу с золотыми нитями. На шее — золотой амулет кобры. Движется как змея — плавно и гипнотически.",
        history: "Нефтис родилась в 1980 в семье жрецов Сета в Каире. Становление приняла в 22, после того как Анубис увидел в ней «дар Сета» — способность будить желания. Переехала в город, чтобы открыть «Лотос» — эзотерический салон, который служит прикрытием для культа и охот. Министерство вышло из Саббата в 2018; Нефтис осталась с Анархами — «свобода — путь Сета».",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 2, dex: 3, sta: 2, cha: 4, man: 3, com: 3, int: 3, wit: 3, res: 2 },
      skills: [
        { key: "persuasion", value: 4, spec: "соблазнение" },
        { key: "subterfuge", value: 3, spec: "тонкая ложь" },
        { key: "performance", value: 3, spec: "танец змеи" },
        { key: "occult", value: 3, spec: "ритуалы Сета" },
        { key: "etiquette", value: 2, spec: "светские салоны" },
        { key: "insight", value: 2, spec: "желания" },
        { key: "streetwise", value: 2, spec: "ночная жизнь" },
        { key: "awareness", value: 1 },
      ],
      disciplines: [
        { key: "presence", value: 3, powers: { 1: "Угроза", 2: "Обаяние", 3: "Возвеличивание" } },
        { key: "obfuscate", value: 2, powers: { 1: "Скрытие лица", 2: "Невидимость духа" } },
        { key: "protean", value: 1, powers: { 1: "Глаза змеи" } },
      ],
      advantages: [
        { id: "herd", rating: 4, note: "Клиенты «Лотоса» — поклонники и адепты культа" },
        { id: "allies", rating: 3, note: "Сеть жрецов Министерства по стране" },
        { id: "resources", rating: 3, note: "Доходы салона и пожертвования культа" },
        { id: "status", rating: 2, note: "Жрица второго круга Министерства" },
        { id: "cc_ministry", rating: 1 },
        { id: "beauty", rating: 2 },
      ],
      gear: {
        haven: "Квартира над «Лотосом», спальня с зеркалами и шелками",
        resources: "Доходы салона + тайные вклады культа",
        items: [
          { name: "Амулет кобры", count: "1", note: "Золотой, знак жречества Сета, фокус для Присутствия" },
          { name: "Сурьма для глаз", count: "1", note: "Ритуальная, по древнему рецепту" },
          { name: "Кадило с миррой", count: "1", note: "Для ритуалов и атмосферы в салоне" },
          { name: "Шёлковый халат", count: "1", note: "Чёрный с золотыми змеями, подарен Анубисом" },
        ],
      },
      trackers: { humanity: 5, hunger: 2, xp: 0 },
    },
  },
  {
    id: "tzimisce-sculptor",
    title: "Скульптор плоти",
    tagline: "Тзимице: художник, чьё полотно — сама плоть",
    portrait: "/vtm/portraits/tzimisce-voivode.jpg",
    sheet: {
      info: {
        name: "Воевода Мирча Дракулешти",
        concept: "Карпатский аристократ-метаморф, хранитель древних земель",
        chronicle: "",
        sire: "Богдан Дракулешти, прадед, ушёл в торпор в 1804",
        occupation: "антиквар и коллекционер «живого искусства»",
        generation: 10,
        sect: "camarilla",
        clan: "tzimisce",
        predator: "trapdoor",
        ambition: "Создать шедевр: идеальную форму жизни из плоти и кости",
        desire: "Найти потомка Дракула, что украл у него древний фолиант",
        principle1: "Искусство требует жертв",
        principle2: "Гости святы — даже те, кого ты лепишь",
        principle3: "Земля помнит своих хозяев",
        anchor1: "Смертная праправнучка Илона, студентка-искусствовед, не знает о нём",
        anchor2: "Карпатское поместье Дракулешти, где он родился и умрёт",
        anchor3: "Костяная чаша семьи, что он никогда не продаст",
        description: "Угловатый мужчина с бледно-серой кожей и острыми чертами лица. Глаза — тёмные, почти чёрные. Костюм — чёрный бархат с меховым воротником. На мизинце — перстень с печатью воеводы. Его лицо — слишком идеально, чтобы быть естественным: оно слеплено.",
        history: "Мирча родился в 1720 в карпатском поместье Дракулешти. Становление принял в 30 от прадеда Богдана. Изучал анатомию в Падуе, искусство во Флоренции, металургию в Праге. Вице в Саббате до 2018, затем перешёл в Камарилью «ради сохранения искусства». Его коллекция «живого искусства» — позор для Человечности, но гордость для Зверя.",
        portrait: "",
        portraitThumb: "",
      },
      attributes: { str: 2, dex: 2, sta: 3, cha: 2, man: 4, com: 3, int: 4, wit: 3, res: 3 },
      skills: [
        { key: "craft", value: 4, spec: "лепка плоти" },
        { key: "medicine", value: 3, spec: "анатомия" },
        { key: "academics", value: 3, spec: "искусство Возрождения" },
        { key: "occult", value: 3, spec: "ритуалы Тзимице" },
        { key: "etiquette", value: 2, spec: "старый свет" },
        { key: "insight", value: 2, spec: "слабости чужих форм" },
        { key: "intimidation", value: 2, spec: "молчаливое уродство" },
        { key: "investigation", value: 1 },
      ],
      disciplines: [
        { key: "vicissitude", value: 3, powers: { 1: "Податливый лик", 2: "Плетение плоти", 3: "Плетение костей" } },
        { key: "auspex", value: 2, powers: { 1: "Обострение чувств", 2: "Потустороннее зрение" } },
        { key: "animalism", value: 1, powers: { 1: "Чутьё на Зверя" } },
      ],
      advantages: [
        { id: "haven", rating: 4, note: "Карпатское поместье + антикварная лавка в городе" },
        { id: "resources", rating: 3, note: "Семейные земли, антиквариат, искусство" },
        { id: "retainers", rating: 3, note: "Два гуля-охранника (слеплены «идеально»)" },
        { id: "status", rating: 2, note: "Воевода Дракулешти, признанный старейшина" },
        { id: "cc_tzimisce", rating: 1 },
        { id: "other_dark_secret", rating: 1, note: "Его «коллекция» в подвале поместья" },
        { id: "myth_land_locked", rating: 1 },
      ],
      gear: {
        haven: "Антикварная лавка «Дракулешти» в городе + карпатское поместье для «особых проектов»",
        resources: "Семейные земли, коллекции антиквариата и искусства",
        items: [
          { name: "Хирургический набор", count: "1", note: "Серебряные скальпели и иглы, семейная реликвия" },
          { name: "Костяная чаша", count: "1", note: "Из черепа прадеда, для ритуалов" },
          { name: "Перстень воеводы", count: "1", note: "Печать Дракулешти, знак власти над землёй" },
          { name: "Фолиант «Книга плоти»", count: "1", note: "Рукописный трактат по Вицисситуде, XVII век" },
        ],
      },
      trackers: { humanity: 4, hunger: 1, xp: 0 },
    },
  },
];

// Название клана для карточки шаблона
export function templateClanName(templateId: string): string {
  return VTM_TEMPLATES.find((t) => t.id === templateId)?.sheet.info.clan || "";
}
